### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by SeanHayes** [eugene1g/font-blast#3]
```
$ node -v
v6.2.0

$ gulp 
/Users/me/dev/web/node_modules/font-blast/lib/glyph-extractor.js:22
var optimizeSvgText = async function optimizeSvgText(svgText) {
                            ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sean/dev/web/node_modules/font-blast/lib/index.js:23:23)
    at Module._compile (module.js:541:32)
```

**Comment by eugene1g** [comment]
My mistake, I only test on the most current version of node. Will resolve shortly.

**Comment by eugene1g** [comment]
Ok I setup basic CircleCI smoketest with node6 and this should be working again

**Comment by SeanHayes** [comment]
Thanks, it's fixed now.
